name: Setup Python dependencies
description: Set up Python, cache pip, and install project dependencies
inputs:
  python-version:
    description: Python version to use
    required: true
  extra-packages:
    description: Optional space-separated list of extra packages to install
    required: false
    default: ''
runs:
  using: composite
  steps:
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ inputs.python-version }}
    - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml') }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install -U pip
        pip install -e .[dev] || pip install -e .
        if [ -n "${{ inputs.extra-packages }}" ]; then
          pip install ${{ inputs.extra-packages }}
        fi
