# Конфіг Zip-CI (заміни під стек за потреби)
staging_dir: ".zipci_staging"
validate: |
  python - <<'PY'
import os,sys
# Базова валідація структури (min-пример)
required = []
missing = [p for p in required if not os.path.exists(p)]
if missing:
  print("Missing:", *missing); sys.exit(1)
print("Structure OK")
PY
test: |
  bash -lc '
    set -e
    if [ -f "pytest.ini" ] || [ -d "tests" ] || [ -f "pyproject.toml" ] || [ -f "requirements.txt" ]; then
      python -m pip -q install -U pip pytest || true
      pytest -q
      exit $?
    fi
    if [ -f "package.json" ]; then
      corepack enable || true
      npm ci --silent || npm install --silent
      if jq -e ".scripts.test" package.json >/dev/null 2>&1; then npm test --silent; else echo "no tests defined (node)"; fi
    fi
    if [ -f "go.mod" ]; then
      go test ./...
    fi
    if [ -f "Cargo.toml" ]; then
      cargo test --quiet
    fi
    if [ -f "Makefile" ] && grep -qE "^test:" Makefile; then
      make test
    fi
    exit 0
  '
