services:
  api:
    build: .
    ports: ["8000:8000"]
    environment:
      - FACTSYNTH_DATABASE_URL=sqlite+aiosqlite:///./data.db
      - FACTSYNTH_RATE_LIMIT=60/minute
    depends_on: [redis]
  redis:
    image: redis:7
    ports: ["6379:6379"]
