site_name: FactSynth
theme: { name: material, features: [navigation.tabs, content.code.copy] }
plugins: [search, mermaid2]
nav:
  - Home: docs/index.md
  - Architecture: docs/architecture.md
  - API: docs/api.md
  - Runbook: docs/runbook.md
