site_name: FactSynth
site_url: https://neuron7x.github.io/FactSynth/
repo_url: https://github.com/neuron7x/FactSynth/

theme:
  name: material

plugins:
  - search
  - redirects
  - minify
  - git-revision-date-localized:
      fallback_to_build_date: true

nav:
  - Home: index.md
  - Production Runbook: prod-runbook.md
  - UI Deployment: ui-deployment.md
  - Prompt Pack: PromptPack.md
  - Incubation Co-Dev UA: INCUBATION_CO_DEV_UA.md
  - FactSynth Lock: FACTSYNTH_LOCK.md
