site_name: FactSynth
site_url: https://neuron7x.github.io/FactSynth/
repo_url: https://github.com/neuron7x/FactSynth/

theme:
  name: material

plugins:
  - search
  - redirects
  - minify
  - git-revision-date-localized

nav:
  - Home: index.md
  - Production Runbook: prod-runbook.md
  - UI Deployment: ui-deployment.md
  - Prompt Pack: PromptPack.md
  - Incubation Co-Dev UA: INCUBATION_CO_DEV_UA.md
  - FactSynth Lock: FACTSYNTH_LOCK.md
  - Models:
      - NLI Token Overlap: models/nli.md
      - LLM Candidate Arbitrator: models/llm_arbitrator.md
  - Datasets:
      - Golden FactSynth: datasets/golden_factsynth.md
      - Golden 12: datasets/golden_12.md
  - Observability:
      - Grafana Dashboard: grafana/dashboards/factsynth-overview.json
      - Prometheus Alerts: config/prometheus/alerts.yml
  - API:
      - OpenAPI Spec: openapi/openapi.yaml
      - Live Docs: https://api.factsynth.example.com/docs
