site_name: FactSynth
theme:
  name: material
nav:
  - Home: index.md
  - Production Runbook: prod-runbook.md
  - UI Deployment: ui-deployment.md
  - Prompt Pack: PromptPack.md
  - Incubation Co-Dev UA: INCUBATION_CO_DEV_UA.md
  - FactSynth Lock: FACTSYNTH_LOCK.md
