site_name: FactSynth
theme:
  name: material
  features: [navigation.tabs, navigation.tracking, content.code.copy, toc.follow]
plugins:
  - search
  - mermaid2
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Ops Runbook: ops/runbook.md
  - API: openapi/
