[project]
name = "factsynth-ultimate-pro"
version = "1.0.1"
description = "Secure, observable FastAPI API for intent reflection & fact synthesis"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "neuron7x"}]
dependencies = [
  "fastapi>=0.110",
  "uvicorn>=0.29",
  "pydantic>=2.7",
  "prometheus-client>=0.20",
  "httpx>=0.27"
]
[project.optional-dependencies]
dev = ["pytest>=8","pytest-cov>=5","ruff>=0.5","pyyaml>=6","mypy>=1.11"]
ops = ["gunicorn>=22"]
otel = ["opentelemetry-sdk>=1.26.0","opentelemetry-instrumentation-fastapi>=0.47b0"]
vault = ["hvac>=2.2.0"]
cache = ["redis>=5.0.0"]
