
[project.optional-dependencies]
cognition = [
    "numpy>=1.24",
    "fastapi>=0.110",
    "pydantic>=2.6"
]
isr = [
    "jax>=0.4.28",
    "diffrax>=0.5.0",
    "typer>=0.12.0"
]
cache = [
    "redis>=5.0",
]

[project.scripts]
fsu-glrtpm = "factsynth_ultimate.glrtpm.pipeline:GLRTPMPipeline"
fsu-isr = "factsynth_ultimate.cli_isr:app"

[tool.ruff]
line-length = 100

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.pytest.ini_options]
addopts = "-q"
