[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "factsynth-ultimate-pro"
version = "1.0.4"
dependencies = [
    "fastapi>=0.116,<0.117",
    "uvicorn>=0.35,<0.36",
    "httpx>=0.28,<0.29",
    "redis>=6.4,<6.5",
    "pydantic>=2.11,<2.12",
    "pydantic-settings>=2.10,<2.11",
    "prometheus-client>=0.22,<0.23",
    "regex>=2025.9,<2026",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4,<8.5",
    "httpx>=0.28,<0.29",
    "uvicorn>=0.35,<0.36",
    "schemathesis>=4.1,<4.2",  # API contract testing
    "websockets>=15.0,<15.1",  # WebSocket test client
    "pytest-cov>=7.0,<7.1",  # coverage plugin
    "requests>=2.32,<2.33",  # HTTP client for contract tests
]
ops = [
    "prometheus-client>=0.22,<0.23",
]
isr = [
    "jax>=0.4.38,<0.5",
    "diffrax>=0.7,<0.8",
]
numpy = [
    "numpy>=1.26,<1.27",
]

[project.scripts]
fsu-api = "factsynth_ultimate.app:create_app"

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B","Q","C90"]
ignore = ["E203","E266","E501"]
target-version = "py310"

[tool.isort]
profile = "black"
line_length = 100

