[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "factsynth-ultimate"
version = "1.0.0"
description = "FactSynth Ultimate API"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
authors = [{name="Ярослав", email="author@example.com"}]
dependencies = [
  "fastapi>=0.110",
  "uvicorn>=0.29",
  "pydantic>=2.7",
  "prometheus-client>=0.20",
]

[project.optional-dependencies]
dev = ["pytest>=8.0", "pytest-cov>=5.0", "ruff>=0.5.0", "mypy>=1.10", "httpx>=0.27", "rich>=13.7"]
ops = ["PyJWT>=2.8"]

[project.scripts]
fsu-api = "factsynth_ultimate.app:main"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "--cov=src --cov-report=term-missing --cov-fail-under=80 -q"
