[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "factsynth-ultimate-pro"
version = "1.0.3"
dependencies = [
    "fastapi",
    "uvicorn",
    "httpx",
    "pydantic>=2.0",
    "pydantic-settings>=2.0",
    "prometheus-client",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "httpx",
    "uvicorn",
]
ops = [
    "prometheus-client",
]

[project.scripts]
fsu-api = "factsynth_ultimate.app:create_app"

