[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "factsynth-ultimate-pro"
version = "1.0.3"
dependencies = [
    "fastapi",
    "uvicorn",
    "httpx",
    "pydantic>=2.0",
    "pydantic-settings>=2.0",
    "prometheus-client",
    "regex",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "httpx",
    "uvicorn",
    "schemathesis",  # API contract testing
    "websockets",  # WebSocket test client
    "pytest-cov",  # coverage plugin
]
ops = [
    "prometheus-client",
]
isr = [
    "jax",
    "diffrax",
]
numpy = [
    "numpy",
]

[project.scripts]
fsu-api = "factsynth_ultimate.app:create_app"

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B","Q","C90"]
ignore = ["E203","E266","E501"]
target-version = "py310"

[tool.isort]
profile = "black"
line_length = 100

