[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "factsynth-ultimate"
version = "0.0.0"
description = "FactSynth — ready product (API/CLI) with tests, CI/CD, Pages."
authors = [{name = "neuron7x"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.110",
  "uvicorn[standard]>=0.24",
  "pydantic>=2.0",
  "prometheus-client>=0.16",
  "requests>=2.31"
]
[project.optional-dependencies]
dev = ["black>=24.3","ruff>=0.6","isort>=5.13","mypy>=1.8","pre-commit>=3.6","yamllint>=1.35"]
test = ["pytest>=8.0","pytest-cov>=5.0","httpx>=0.27","openapi-spec-validator>=0.7.1","pyyaml>=6.0.1"]
[project.scripts]
factsynth = "factsynth_ultimate.cli:main"
factsynth-ultimate = "factsynth_ultimate.cli:main"
[tool.setuptools]
package-dir = {"" = "src"}
[tool.setuptools.packages.find]
where = ["src"]
include = ["factsynth_ultimate*"]
