[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "factsynth-ultimate"
version = "2.0.0"
description = "FactSynth Ultimate — unified Intent→Insight engine + GLRTPM role orchestrator (R–I–P–Ω), API/CLI/UI, tests, Docker/K8s, CI, coverage."
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
authors = [{name="Ярослав (Author)", email="author@example.com"}]
dependencies = [
  "fastapi>=0.110,<0.115",
  "uvicorn[standard]>=0.24,<0.31",
  "pydantic>=2,<3",
  "regex>=2024.5.15",
  "prometheus-client>=0.16,<1",
  "requests>=2.31,<3",
  "typer>=0.12",
  "orjson>=3.10",
  "numpy>=1.26",
  "scikit-learn>=1.4",
  "markdown>=3.6"
]
[project.optional-dependencies]
dev = ["pytest>=8.0,<9","pytest-cov>=5.0,<6","ruff>=0.5.0","mypy>=1.10","httpx>=0.27,<0.28","rich>=13.7"]
ops = ["PyJWT>=2.8"]
[project.scripts]
fsu = "factsynth_ultimate.cli:app"
fsu-api = "factsynth_ultimate.api:run"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "--cov=src --cov-report=term-missing --cov-fail-under=90 -q"
