[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "factsynth-ultimate-pro"
version = "1.0.4"
dependencies = [
    "fastapi>=0.116,<0.117",
    "uvicorn>=0.35,<0.36",
    "httpx>=0.28,<0.29",
    "pydantic>=2.11,<2.12",
    "pydantic-settings>=2.10,<2.11",
    "prometheus-client>=0.22,<0.23",
    "regex>=2025.9,<2026",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "httpx",
    "uvicorn",
    "schemathesis",  # API contract testing
    "websockets",  # WebSocket test client
    "pytest-cov",  # coverage plugin
]
ops = [
    "prometheus-client>=0.22,<0.23",
]
isr = [
    "jax",
    "diffrax",
]
numpy = [
    "numpy",
]

[project.scripts]
fsu-api = "factsynth_ultimate.app:create_app"

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B","Q","C90"]
ignore = ["E203","E266","E501"]
target-version = "py310"

[tool.isort]
profile = "black"
line_length = 100

