[project]
name = "factsynth-ultimate-pro"
version = "1.0.3"
dependencies = [
    "fastapi",
    "prometheus-client",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "httpx",
    "uvicorn",
]
