line-length = 100
target-version = "py310"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[lint]
select = ["E", "F", "I", "N", "UP", "B", "SIM", "S", "C4", "PIE", "Q", "RUF"]
ignore = ["E501"]
