openapi: 3.0.3
info:
  title: FactSynth Ultimate API
  version: "1.0.0"
servers:
  - url: http://localhost:8000
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
paths:
  /v1/intent_reflector:
    post:
      security:
        - ApiKeyAuth: []
      summary: Reflect user intent into structured insight
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntentReq'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  insight: { type: string }
  /v1/score:
    post:
      security:
        - ApiKeyAuth: []
      summary: Score content against rubric
      requestBody:
        required: false
      responses:
        '200':
          description: OK
  /v1/stream:
    post:
      security:
        - ApiKeyAuth: []
      summary: Stream insights (SSE)
      responses:
        '200':
          description: OK
          content:
            text/event-stream: {}
  /v1/glrtpm/run:
    post:
      security:
        - ApiKeyAuth: []
      summary: Run GLRTPM pipeline
      responses:
        '200':
          description: OK
  /v1/healthz:
    get:
      summary: Health probe
      responses:
        '200':
          description: OK
  /metrics:
    get:
      summary: Prometheus metrics
      responses:
        '200':
          description: OK
components:
  schemas:
    IntentReq:
      type: object
      properties:
        intent: { type: string }
        length: { type: integer, default: 100 }
