openapi: 3.0.3
info: { title: FactSynth API, description: Minimal contract, version: "" }
servers: [ { url: http://localhost:8000 } ]
paths:
/healthz: { get: { summary: Liveness, responses: { '200': { description: OK } } } }
/metrics: { get: { summary: Prometheus metrics, responses: { '200': { description: OK } } } }
/v1/generate:
post:
summary: Synthesize output
requestBody:
required: true
content: { application/json: { schema: { type: object, properties:
{ prompt: { type: string, minLength: 1 }, max_tokens: { type: integer, minimum: 1, maximum: 4096, default: 128 } }, required: [prompt] } } }
responses: { '200': { description: OK, content: { application/json: { schema: { type: object, properties: { output: { type: string } } } } } } }
