openapi: 3.0.3
info:
  title: FactSynth Ultimate API
  version: "1.0.0"
servers:
  - url: http://localhost:8000
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    IntentReq:
      type: object
      properties:
        intent:
          type: string
        length:
          type: integer
          default: 100
    ScoreRequest:
      type: object
      properties:
        text:
          type: string
        targets:
          type: array
          items:
            type: string
    ScoreResponse:
      type: object
      properties:
        score:
          type: number
          format: float
    StreamRequest:
      type: object
      properties:
        text:
          type: string
    GLRTPMRequest:
      type: object
      properties:
        text:
          type: string
paths:
  /v1/intent_reflector:
    post:
      security:
        - ApiKeyAuth: []
      summary: Reflect user intent into structured insight
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntentReq'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  insight:
                    type: string
  /v1/score:
    post:
      security:
        - ApiKeyAuth: []
      summary: Score content against rubric
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScoreRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScoreResponse'
  /v1/stream:
    post:
      security:
        - ApiKeyAuth: []
      summary: Stream insights (SSE)
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StreamRequest'
      responses:
        '200':
          description: OK
          content:
            text/event-stream: {}
  /v1/glrtpm/run:
    post:
      security:
        - ApiKeyAuth: []
      summary: Run GLRTPM pipeline
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GLRTPMRequest'
      responses:
        '200':
          description: OK
  /v1/healthz:
    get:
      summary: Health probe
      responses:
        '200':
          description: OK
  /metrics:
    get:
      summary: Prometheus metrics
      responses:
        '200':
          description: OK
