{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: factsynth-allow-ingress
spec:
  podSelector:
    matchLabels:
      app: factsynth
  policyTypes:
    - Ingress
  ingress:
{{- range .Values.networkPolicy.ingress }}
    - from:
{{- range .from }}
{{- if .podSelector }}
        - podSelector:
{{ toYaml .podSelector | indent 10 }}
{{- end }}
{{- if .namespaceSelector }}
        - namespaceSelector:
{{ toYaml .namespaceSelector | indent 10 }}
{{- end }}
{{- if .ipBlock }}
        - ipBlock:
{{ toYaml .ipBlock | indent 10 }}
{{- end }}
{{- end }}
      ports:
{{- if .ports }}
{{- range .ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port | default $.Values.service.port }}
{{- end }}
{{- else }}
        - protocol: TCP
          port: {{ $.Values.service.port }}
{{- end }}
{{- end }}
{{- end }}
