apiVersion: apps/v1
kind: Deployment
metadata: { name: factsynth }
spec:
replicas: 2
selector: { matchLabels: { app: factsynth } }
template:
metadata: { labels: { app: factsynth } }
spec:
containers:
- name: api
image: ghcr.io/neuron7x/factsynth:latest
ports: [ { containerPort: 8000 } ]
readinessProbe: { httpGet: { path: /healthz, port: 8000 }, initialDelaySeconds: 5, periodSeconds: 10 }
livenessProbe:  { httpGet: { path: /healthz, port: 8000 }, initialDelaySeconds: 5, periodSeconds: 10 }
------------------------------------------------------------------------------------------------------

apiVersion: v1
kind: Service
metadata: { name: factsynth }
spec:
selector: { app: factsynth }
ports: [ { port: 80, targetPort: 8000, protocol: TCP } ]
