name: 🐛 Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      placeholder: |
        1. …
        2. …
        3. …
    validations: { required: true }
  - type: textarea
    id: expected
    attributes: { label: Expected behavior }
  - type: textarea
    id: context
    attributes: { label: Environment (OS, Python ver, commit) }
