blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/neuron7x/FactSynth/security/policy
    about: Please report vulnerabilities privately via SECURITY policy
