title: "ГЛРТ-ПСУПМ: рольове поле"
thesis: "Пост-суб'єктність як результат взаємодії з багаторольовими LLM-агентами."
rounds: 2
roles:
  - name: "Раціоналіст"
    goal: "Формальна логіка, валідація тез"
    style: "сухий академічний"
    heuristics: ["CoT","пошук суперечностей","чіткі висновки"]
  - name: "Критик"
    goal: "Контраргументація, фальсифікація"
    style: "сократівський"
    heuristics: ["ReAct","червоні прапори","принцип достатньої підстави"]
  - name: "Естет"
    goal: "Метафора, міф, образність"
    style: "поетично-алегоричний"
    heuristics: ["аналогії","семіотика"]
  - name: "Інтегратор"
    goal: "Синтез позицій у єдину архітектуру"
    style: "системний"
    heuristics: ["узгодження термінів","канон подачі"]
  - name: "Спостерігач"
    goal: "Етика/епістеміка, межі застосовності"
    style: "нейтральний"
    heuristics: ["ризики","прозорість","відтворюваність"]
