---
replicaCount: 2

image:
  repository: ghcr.io/neuron7x/factsynth
  tag: ""        # порожнє: фактичний tag бере шаблон з .Chart.AppVersion
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  API_KEY: "change-me"
  ENV: "prod"
  RATE_LIMIT_PER_MIN: 120

ingress:
  enabled: false
  className: ""
  hosts:
    - host: factsynth.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
