---
replicaCount: 2

image:
  repository: ghcr.io/neuron7x/factsynth
  tag: ""        # порожнє: фактичний tag бере шаблон з .Chart.AppVersion
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  ENV: "prod"
  RATE_LIMIT_REDIS_URL: redis://redis:6379/0
  RATE_LIMIT_PER_KEY: 120
  RATE_LIMIT_PER_IP: 120
  RATE_LIMIT_PER_ORG: 120
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
  OTEL_SERVICE_NAME: ""

secrets:
  name: factsynth-secret
  apiKey: "change-me"

ingress:
  enabled: false
  className: ""
  host: factsynth.local
  tls: []

resources: {}

securityContext:
  pod: {}
  container: {}

startupProbe:
  httpGet:
    path: /v1/healthz
    port: 8000
  failureThreshold: 30
  periodSeconds: 10

otelCollector:
  enabled: false
  image:
    repository: otel/opentelemetry-collector
    tag: latest
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch: {}
    exporters:
      logging: {}
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60

networkPolicy:
  enabled: false
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8000

pdb:
  enabled: false
  minAvailable: 1

alerts:
  enabled: true
  latencyP95Threshold: 0.5
  errorRateThreshold: 0.05

namespace:
  create: false
  name: factsynth
