---
replicaCount: 2

image:
  repository: ghcr.io/neuron7x/factsynth
  tag: ""        # порожнє: фактичний tag бере шаблон з .Chart.AppVersion
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  ENV: "prod"
  RATE_LIMIT_PER_MIN: 120

secrets:
  name: factsynth-secret
  apiKey: "change-me"

ingress:
  enabled: false
  className: ""
  host: factsynth.local
  tls: []

resources: {}

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60

networkPolicy:
  enabled: false

pdb:
  enabled: false
  minAvailable: 1

namespace:
  create: false
  name: factsynth
