---
replicaCount: 2

image:
  repository: ghcr.io/neuron7x/factsynth
  tag: ""        # порожнє: фактичний tag бере шаблон з .Chart.AppVersion
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  API_KEY: "change-me"
  ENV: "prod"
  RATE_LIMIT_PER_MIN: 120
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  OTEL_SERVICE_NAME: "factsynth"

ingress:
  enabled: false
  className: ""
  hosts:
    - host: factsynth.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

otelCollector:
  enabled: true
  image: otel/opentelemetry-collector:0.92.0
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
        loglevel: debug
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          exporters: [logging]
