name: Release Artifacts
on:
  workflow_dispatch:
  push:
    tags: [ 'v*.*.*' ]
permissions: { contents: write }
concurrency: { group: release-${{ github.ref }}, cancel-in-progress: true }
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with: { node-version: 'lts/*', cache: 'npm' }
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with: { python-version: '3.11', cache: 'pip' }
      - name: Install deps
        run: |
          [ -f package.json ] && npm ci || true
          [ -f requirements.txt ] && python -m pip install -U pip && pip install -r requirements.txt || true
      - name: Build
        run: |
          [ -f package.json ] && npm run build || true
      - name: Create zip
        run: |
          mkdir -p dist
          git archive -o dist/factsynth-${{ github.ref_name }}.zip --format zip HEAD
      - name: Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836
        with: { files: dist/*.zip }
