name: Release Artifacts
on:
  workflow_dispatch:
  push:
    tags: [ 'v*.*.*' ]
permissions: { contents: write }
concurrency: { group: release-${{ github.ref }}, cancel-in-progress: true }
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-node@v5
        with: { node-version: 'lts/*', cache: 'npm' }
      - uses: actions/setup-python@v6
        with: { python-version: '3.11', cache: 'pip' }
      - name: Install deps
        run: |
          [ -f package.json ] && npm ci || true
          [ -f requirements.txt ] && python -m pip install -U pip && pip install -r requirements.txt || true
      - name: Build
        run: |
          [ -f package.json ] && npm run build || true
      - name: Create zip
        run: |
          mkdir -p dist
          git archive -o dist/factsynth-${{ github.ref_name }}.zip --format zip HEAD
      - name: Release
        uses: softprops/action-gh-release@v2
        with: { files: dist/*.zip }
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
