name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
permissions: { contents: read }
concurrency: { group: ci-${{ github.ref }}, cancel-in-progress: true }
jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      API_KEY: change-me
      RATE_LIMIT_REDIS_URL: redis://test
      RATE_LIMIT_PER_KEY: "1000"
      RATE_LIMIT_PER_IP: "1000"
      RATE_LIMIT_PER_ORG: "1000"
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v5
        with: { node-version: 'lts/*', cache: 'npm' }

      - uses: actions/setup-python@v6
        with: { python-version: '3.11', cache: 'pip' }

      - name: Install JS deps
        if: hashFiles('package.json') != ''
        run: |
          if [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i --frozen-lockfile;
          elif [ -f yarn.lock ]; then corepack enable && yarn install --immutable;
          elif [ -f package-lock.json ]; then npm ci;
          else echo "No JS lockfile, skipping strict install"; fi

      - name: Install Python deps
        if: hashFiles('requirements.txt','requirements-dev.txt','pyproject.toml') != ''
        run: |
          python -m pip install -U pip
          [ -f requirements.txt ] && pip install -r requirements.txt
          [ -f requirements-dev.txt ] && pip install -r requirements-dev.txt
          [ -f pyproject.toml ] && pip install ".[dev]" || true

      - name: Lint JS
        if: hashFiles('package.json') != ''
        run: |
          npx --yes eslint --version >/dev/null 2>&1 || npm i -D eslint
          if [ -f .eslintrc* ] || npx --yes eslint --print-config . >/dev/null 2>&1; then
            npx eslint . --max-warnings=0
          else
            echo "No ESLint config; skipping."
          fi

      - name: Lint Python
        if: hashFiles('pyproject.toml','requirements.txt') != ''
        run: |
          pip install ruff
          ruff check .

      - name: Unit tests (JS)
        if: hashFiles('package.json') != ''
        run: |
          if npm run -s | grep -qE '^ *test'; then
            npm test --silent -- --ci || npm run test -- --ci
          else
            echo "No JS test script; skipping."
          fi

      - name: Unit tests (Python)
        if: hashFiles('tests/**','pyproject.toml','requirements.txt') != ''
        run: |
          pip install pytest
          pytest -q

      - name: Build docs (MkDocs)
        if: hashFiles('mkdocs.yml') != ''
        run: |
          pip install mkdocs mkdocs-material
          mkdocs build -q

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ci-failures
          if-no-files-found: ignore
          path: |
            **/junit*.xml
            **/coverage*
            site/**
