name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
permissions: { contents: read }
concurrency: { group: ci-${{ github.ref }}, cancel-in-progress: true }
jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    env:
      API_KEY: change-me
      RATE_LIMIT_REDIS_URL: redis://test
      RATE_LIMIT_PER_KEY: "1000"
      RATE_LIMIT_PER_IP: "1000"
      RATE_LIMIT_PER_ORG: "1000"
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements.lock
            pyproject.toml

      - name: Install JS deps
        if: hashFiles('package.json') != ''
        run: |
          if [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i --frozen-lockfile;
          elif [ -f yarn.lock ]; then corepack enable && yarn install --immutable;
          elif [ -f package-lock.json ]; then npm ci;
          else echo "No JS lockfile, skipping strict install"; fi

      - name: Install Python deps
        if: hashFiles('requirements.txt','requirements.lock','pyproject.toml') != ''
        run: |
          python -m pip install -U pip
          if [ -f requirements.lock ]; then
            pip install -r requirements.lock
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          [ -f pyproject.toml ] && pip install -e .[dev] || true

      - name: Check lockfile
        if: hashFiles('requirements.lock','pyproject.toml') != ''
        run: |
          pip-compile pyproject.toml --allow-unsafe --extra=dev --extra=isr --extra=numpy --generate-hashes --output-file=requirements.lock
          git diff --exit-code requirements.lock

      - name: Check dev requirements
        if: hashFiles('pyproject.toml','requirements-dev.txt') != ''
        run: |
          scripts/update_dev_requirements.sh
          git diff --exit-code requirements-dev.txt

      - name: Lint JS
        if: hashFiles('package.json') != ''
        run: |
          npx --yes eslint --version >/dev/null 2>&1 || npm i -D eslint
          if [ -f .eslintrc* ] || npx --yes eslint --print-config . >/dev/null 2>&1; then
            npx eslint . --max-warnings=0
          else
            echo "No ESLint config; skipping."
          fi

      - name: Ruff
        if: hashFiles('pyproject.toml','requirements.txt') != ''
        run: |
          pip install ruff
          ruff check .

      - name: Mypy
        if: hashFiles('pyproject.toml','requirements.txt') != ''
        run: |
          pip install mypy
          mypy .

      - name: Bandit
        if: hashFiles('pyproject.toml','requirements.txt') != ''
        run: |
          pip install bandit
          bandit -r .

      - name: Safety
        if: hashFiles('requirements.txt','requirements.lock','pyproject.toml') != ''
        run: |
          pip install safety
          safety check --full-report

      - name: pip-audit
        if: hashFiles('requirements.txt','requirements.lock','pyproject.toml') != ''
        run: |
          pip install pip-audit
          pip-audit

      - name: npm audit
        if: hashFiles('package-lock.json') != ''
        run: npm audit --production

      - name: Unit tests (JS)
        if: hashFiles('package.json') != ''
        run: |
          if npm run -s | grep -qE '^ *test'; then
            npm test --silent -- --ci || npm run test -- --ci
          else
            echo "No JS test script; skipping."
          fi

      - name: Unit tests (Python)
        if: hashFiles('tests/**','pyproject.toml','requirements.txt') != ''
        run: |
          pip install pytest
          pytest -q

      - name: Fairness tests
        if: hashFiles('fairness_tests/**','pyproject.toml','requirements.txt') != ''
        run: |
          pip install pytest
          pytest -q fairness_tests

      - name: Build docs (MkDocs)
        if: hashFiles('mkdocs.yml') != ''
        run: |
          pip install mkdocs mkdocs-material
          mkdocs build -q

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: ci-failures-${{ matrix.python-version }}
          if-no-files-found: ignore
          path: |
            **/junit*.xml
            **/coverage*
            site/**

  container-scan:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: .
          load: true
          tags: factsynth:ci
      - uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: factsynth:ci
          format: sarif
          output: trivy.sarif
          severity: HIGH,CRITICAL
      - uses: github/codeql-action/upload-sarif@528ca598d956c91826bd742262cdfc5d02b77710
        with:
          sarif_file: trivy.sarif
