name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
permissions: { contents: read }
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { python-version: [ "3.10", "3.11", "3.12" ] }
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with: { python-version: ${{ matrix.python-version }} }
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .[dev] || pip install -e .
      - name: Test
        env: { PYTHONPATH: src }
        run: pytest -q --maxfail=1 --disable-warnings --cov=src/factsynth_ultimate --cov-report=xml:coverage.xml
      - name: Check coverage threshold
        run: |
          python - <<'PY'
          import sys
          import xml.etree.ElementTree as ET
          coverage = float(ET.parse('coverage.xml').getroot().get('line-rate')) * 100
          print(f"Total coverage: {coverage:.2f}%")
          if coverage < 85:
              sys.exit("Coverage below 85%")
          PY
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with: { name: coverage-xml-${{ matrix.python-version }}, path: coverage.xml }

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with: { python-version: "3.12" }
      - name: Install ruff
        run: |
          python -m pip install -U pip
          pip install ruff
      - name: Ruff
        run: ruff check .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with: { python-version: "3.12" }
      - name: Install mypy
        run: |
          python -m pip install -U pip
          pip install mypy
          pip install -e .[dev] || pip install -e .
      - name: Mypy
        run: mypy src
