name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files | tee pre-commit.log
      - name: Upload lint logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-logs
          path: pre-commit.log

  type-check:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install mypy types-requests types-PyYAML
      - name: Run mypy
        run: mypy . | tee mypy.log
      - name: Upload type-check logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mypy-logs
          path: mypy.log

  tests:
    runs-on: ubuntu-latest
    needs: type-check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.lock
          pip install -r requirements-dev.txt
          pip install fakeredis
      - name: Run tests
        run: pytest --maxfail=1 --cov=src --cov-report=xml | tee pytest.log
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs
          path: pytest.log
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
