name: ci
on:
  push: {branches: [main]}
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports: ["6379:6379"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.10'}
      - run: pip install -U pip
      - run: pip install -e .[dev]
      - run: ruff check .
      - run: mypy .
      - run: pytest --cov=.
      - name: Quality Gate
        run: python scripts/quality_gate.py
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        if: always()
