name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "*" ]

jobs:
  tests:
    name: unit+property (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    env:
      API_KEY: change-me
      PYTHONWARNINGS: default
      HYPOTHESIS_PROFILE: ci
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip wheel setuptools
          # project + dev dependencies
          pip install -e .[dev] || true
          # sanity for tests/streams
          pip install "pytest>=8" hypothesis anyio "httpx>=0.27" asgi_lifespan fastapi uvicorn

      - name: Pytest (fast)
        run: |
          pytest -q -m "not slow" --maxfail=1

  smoke-streams:
    name: smoke (SSE/WS)
    runs-on: ubuntu-latest
    needs: [ tests ]
    env:
      API_KEY: change-me
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev] || true
          pip install "pytest>=8" anyio "httpx>=0.27" asgi_lifespan fastapi uvicorn

      - name: Smoke (SSE/WS only)
        run: |
          # run only tests marked smoke
          pytest -q -m smoke -k "stream" --maxfail=1
