name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Lint/Types/Tests (py${{ matrix.py }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py: ["3.11","3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py }}
          cache: "pip"
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .[dev,ops] || pip install -e .
          pip install -U ruff mypy pytest pytest-cov
      - name: Ruff
        run: ruff check . --output-format=github
        continue-on-error: true
      - name: MyPy
        run: mypy --install-types --non-interactive
        continue-on-error: true
      - name: PyTest (coverage)
        env:
          PYTHONPATH: src
        run: pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=xml:coverage.xml
      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.py }}
          path: coverage.xml
