name: CI
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    name: Quality (ruff/mypy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12", cache: "pip" }
      - name: Install tools
        run: |
          python -m pip install -U pip
          pip install -U ruff mypy
      - name: Ruff
        run: ruff check . --output-format=github
        continue-on-error: true
      - name: MyPy
        run: mypy --install-types --non-interactive || true
        continue-on-error: true

  tests:
    name: PyTest
    needs: quality
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev,ops] || pip install -e .
          pip install -U pytest pytest-cov
      - name: Run tests
        env: { PYTHONPATH: src }
        run: |
          pytest tests --disable-warnings --cov=src --cov-report=xml:coverage.xml
          mv .coverage .coverage.${{ matrix.py }}
      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.py }}
          path: |
            .coverage.${{ matrix.py }}
            coverage.xml

  coverage:
    name: Combine coverage
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Download coverage data
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          merge-multiple: true
          path: coverage
      - name: Combine coverage
        run: |
          python -m pip install -U pip
          pip install coverage
          coverage combine coverage
          coverage xml -o coverage.xml
      - name: Upload combined coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-combined
          path: coverage.xml
