name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
permissions: { contents: read }
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { python-version: [ "3.10", "3.11", "3.12" ] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .[dev] || pip install -e .
      - name: Test
        env: { PYTHONPATH: src }
        run: pytest -q --maxfail=1 --disable-warnings --cov=src/factsynth_ultimate --cov-report=xml:coverage.xml
      - uses: actions/upload-artifact@v4
        with: { name: coverage-xml-${{ matrix.python-version }}, path: coverage.xml }
