name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "*" ]

jobs:
  tests:
    name: unit+property (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    env:
      API_KEY: change-me
      PYTHONWARNINGS: default
      HYPOTHESIS_PROFILE: ci
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip wheel setuptools
          pip install --require-hashes -r requirements.lock
          # Install testing/dev extras
          pip install -r requirements-dev.txt
          pip install numpy hypothesis diffrax jax schemathesis
          pip install -e . --no-deps
          npm install -g @stoplight/spectral-cli@6

      - name: Check version consistency
        run: python tools/check_version.py

      - name: Run tests
        run: pytest --cov=src --cov-report=xml

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml

      - name: Spectral lint
        run: spectral lint openapi/openapi.yaml

      - name: Dependency audit
        run: pip-audit -r requirements.lock

  smoke-streams:
    name: smoke (SSE/WS)
    runs-on: ubuntu-latest
    needs: [ tests ]
    env:
      API_KEY: change-me
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install --require-hashes -r requirements.lock
          # Install testing/dev extras
          pip install -r requirements-dev.txt
          pip install numpy hypothesis diffrax jax schemathesis
          pip install -e . --no-deps

      - name: Smoke (SSE/WS only)
        run: |
          # run only tests marked smoke
          pytest -q -m smoke -k "stream" --maxfail=1
