name: Container Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to tag the image with (without the leading v)'
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Release version to tag the image with (without the leading v)'
        required: false
        type: string
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.docker/**'
      - 'src/**'

concurrency:
  group: container-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  packages: write
  id-token: write
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Determine release version
        id: release_version
        run: |
          version="$(jq -r '.inputs.version // ""' "$GITHUB_EVENT_PATH")"
          echo "RELEASE_VERSION=$version" >>"$GITHUB_ENV"
          echo "version=$version" >>"$GITHUB_OUTPUT"
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=semver,pattern={{version}},value=${{ steps.release_version.outputs.version }},enable=${{ steps.release_version.outputs.version != '' }}
      - name: Export image reference
        run: echo "IMAGE_REF=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >>"$GITHUB_ENV"
      - uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        id: build
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ (steps.meta.outputs.version != '' && format('{0}:v{1}', env.IMAGE_REF, steps.meta.outputs.version)) || '' }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20
      - uses: anchore/sbom-action/download-syft@e8d2a6937ecead383dfe75190d104edd1f9c5751
      - name: Generate SBOM (SPDX JSON)
        run: syft ${{ env.IMAGE_REF }}@${{ steps.build.outputs.digest }} -o spdx-json --file sbom.spdx.json
      - name: Sign container image
        env:
          COSIGN_YES: 'true'
          COSIGN_EXPERIMENTAL: '1'
        run: cosign sign ${{ env.IMAGE_REF }}@${{ steps.build.outputs.digest }}
      - name: Attach SBOM attestation
        env:
          COSIGN_YES: 'true'
          COSIGN_EXPERIMENTAL: '1'
        run: cosign attest --predicate sbom.spdx.json --type spdx ${{ env.IMAGE_REF }}@${{ steps.build.outputs.digest }}
