name: Container Scan
on:
  schedule: [ { cron: '11 4 * * 1' } ]
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.docker/**'
permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: container-scan-${{ github.ref }}
      cancel-in-progress: true
    env:
      TRIVY_CACHE_DIR: trivy-cache
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: trivy-cache
          key: trivy-${{ runner.os }}-${{ hashFiles('Dockerfile') }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: factsynth:ci
      - uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: factsynth:ci
          format: sarif
          output: trivy.sarif
          severity: HIGH,CRITICAL
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif
