name: Container Scan
on:
  schedule: [ { cron: '11 4 * * 1' } ]
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.docker/**'
permissions:
  contents: read
  security-events: write
jobs:
  trivy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency: { group: container-scan-${{ github.ref }}, cancel-in-progress: true }
    env: { TRIVY_CACHE_DIR: trivy-cache }
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: trivy-cache
          key: trivy-${{ runner.os }}-${{ hashFiles('Dockerfile') }}
      - uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: .
          load: true
          tags: factsynth:ci
      - uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          image-ref: factsynth:ci
          format: sarif
          output: trivy.sarif
          severity: HIGH,CRITICAL
      - uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3
        with: { sarif_file: trivy.sarif }
