---
name: Container Release
'on':
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  workflow_dispatch:

concurrency:
  group: container-release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/factsynth
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch
            type=ref,event=tag
            type=sha
      - name: Build & push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ENV=prod

  trivy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Scan image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          # yamllint disable rule:line-length
          image-ref: ghcr.io/${{ github.repository_owner }}/factsynth@${{ needs.build.outputs.digest }}
          # yamllint enable rule:line-length
          ignore-unfixed: true
          exit-code: '1'
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

  sbom:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          # yamllint disable rule:line-length
          image: ghcr.io/${{ github.repository_owner }}/factsynth@${{ needs.build.outputs.digest }}
          # yamllint enable rule:line-length
          format: spdx-json
          output-file: sbom.spdx.json
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

  smoke:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull exact image
        run: docker pull ghcr.io/${{ github.repository_owner }}/factsynth@${{ needs.build.outputs.digest }}
      - name: Run & probe
        shell: bash
        run: |
          docker run -d --rm -p 8000:8000 \
            --name factsynth \
            ghcr.io/${{ github.repository_owner }}/factsynth@${{ needs.build.outputs.digest }}
          for i in $(seq 1 45); do
            curl -fsS http://127.0.0.1:8000/v1/healthz && exit 0 || sleep 2
          done
          echo "Health check failed; recent logs:" >&2
          docker logs --tail=200 factsynth >&2
          exit 1
