name: docker
on:
  push:
    tags: ["v*.*.*"]
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions: {packages: write, contents: read}
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: docker build -t ghcr.io/${{ github.repository_owner }}/factsynth:${{ github.ref_name }} .
      - name: Push
        run: docker push ghcr.io/${{ github.repository_owner }}/factsynth:${{ github.ref_name }}
      - name: Latest tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/factsynth:${{ github.ref_name }} ghcr.io/${{ github.repository_owner }}/factsynth:latest
          docker push ghcr.io/${{ github.repository_owner }}/factsynth:latest
