name: Docs Build
on:
  pull_request: { branches: [ main ] }
permissions: { contents: read }
jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with: { python-version: '3.11', cache: 'pip' }
      - name: Install docs dependencies
        run: |
          python -m pip install -U pip
          pip install -r docs/requirements.txt
      - name: Build docs
        run: mkdocs build --strict
