name: Docs Quality
on:
  pull_request:
    paths:
      - '**/*.md'
      - '.github/workflows/docs-quality.yml'
jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: davidanson/markdownlint-cli2-action@v17
        with:
          globs: |
            **/*.md
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install markdown-link-check
        run: npm i -g markdown-link-check
      - name: Check links
        run: |
          find . -name "*.md" -not -path "./node_modules/*" -print0 | \
          xargs -0 -n1 -I{} bash -c 'echo "::group::{}"; markdown-link-check -q "{}"; ec=$?; echo "::endgroup::"; exit $ec'
