name: E2E & Load
on:
  workflow_dispatch:
  schedule: [ { cron: '0 1 * * 2' } ]
permissions: { contents: read }
concurrency: { group: 'e2e-${{ github.ref }}', cancel-in-progress: true }
jobs:
  e2e:
    if: hashFiles('e2e/**','tests/e2e/**') != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with: { node-version: 'lts/*', cache: 'npm' }
      - run: |
          npm ci || true
          npx playwright install --with-deps || true
          if npm run -s | grep -qE '^ *e2e'; then npm run e2e --if-present; else echo "No e2e script"; fi
  k6:
    if: hashFiles('k6/**','load/**') != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/k6-action@v0.3.1
        with:
          filename: |
            k6/**/*.js
            load/**/*.js
