name: e2e load

on:
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/setup-k6-action@v1
        with:
          docker-options: --add-host=host.docker.internal:host-gateway
      - name: Run k6 test
        run: k6 run test.js
