name: helm-chart

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Package chart
        run: helm package charts/factsynth
      - name: Push chart
        env:
          HELM_REGISTRY: ghcr.io/${{ github.repository_owner }}/charts
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
          helm push factsynth-*.tgz oci://$HELM_REGISTRY
