name: helm-chart

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
      - name: Package chart
        run: helm package charts/factsynth
      - name: Push chart
        env:
          HELM_REGISTRY: ghcr.io/${{ github.repository_owner }}/charts
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
          helm push factsynth-*.tgz oci://$HELM_REGISTRY
