name: Link Check
on:
  pull_request:
  schedule: [{ cron: "0 6 * * 1" }]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose --no-progress
            --require-https
            --retry-wait 2 --max-retries 2
            --accept 200,206,429
            --exclude-all-private
            .
