name: Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      STRICT_FAIL_FATAL: ${{ vars.STRICT_FAIL_FATAL || 'false' }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"
          cache: "pip"
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: "20"
          cache: "npm"
      - name: Install docs deps
        run: pip install -r docs/requirements.txt
      - name: Build MkDocs (strict, fallback non-strict)
        id: mkdocs
        run: |
          set +e
          mkdocs build --strict --site-dir site 2>&1 | tee strict.log
          strict_exit=${PIPESTATUS[0]}
          set -e
          if [ "$strict_exit" -ne 0 ]; then
            echo "strict_failed=true" >> "$GITHUB_OUTPUT"
            echo "::warning::Strict build failed - retrying non-strict"
            echo "⚠️ Strict build failed. See strict.log" >> "$GITHUB_STEP_SUMMARY"
            mkdocs build --site-dir site
            if [ "$STRICT_FAIL_FATAL" = "true" ]; then
              exit "$strict_exit"
            fi
          fi
      - name: Smoke test MkDocs serve
        run: |
          timeout 15s mkdocs serve --watch >/tmp/mkdocs-serve.log 2>&1 || exit_code=$?
          if [ "${exit_code:-0}" != "124" ]; then
            cat /tmp/mkdocs-serve.log
            exit "${exit_code:-1}"
          fi
      - name: Upload strict build log
        if: steps.mkdocs.outputs.strict_failed == 'true'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: strict-log
          path: strict.log
      - name: Build ReDoc (OpenAPI)
        run: |
          mkdir -p site/openapi
          if [ -f openapi/openapi.yaml ]; then
            npx --yes redoc-cli@0.13.23 bundle openapi/openapi.yaml -o site/openapi/index.html
          else
            echo "<!doctype html><title>No OpenAPI</title><p>No openapi/openapi.yaml</p>" > site/openapi/index.html
          fi
      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b
      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
