name: Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRICT_FAIL_FATAL: ${{ vars.STRICT_FAIL_FATAL || 'false' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "npm"
      - name: Install docs deps
        run: pip install -r docs/requirements.txt
      - name: Build MkDocs (strict, fallback non-strict)
        id: mkdocs
        run: |
          set +e
          mkdocs build --strict --site-dir site 2>&1 | tee strict.log
          strict_exit=${PIPESTATUS[0]}
          set -e
          if [ "$strict_exit" -ne 0 ]; then
            echo "strict_failed=true" >> "$GITHUB_OUTPUT"
            echo "::warning::Strict build failed - retrying non-strict"
            echo "⚠️ Strict build failed. See strict.log" >> "$GITHUB_STEP_SUMMARY"
            mkdocs build --site-dir site
            if [ "$STRICT_FAIL_FATAL" = "true" ]; then
              exit "$strict_exit"
            fi
          fi
      - name: Upload strict build log
        if: steps.mkdocs.outputs.strict_failed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: strict-log
          path: strict.log
      - name: Build ReDoc (OpenAPI)
        run: |
          mkdir -p site/openapi
          if [ -f openapi/openapi.yaml ]; then
            npx --yes redoc-cli@0.13.23 bundle openapi/openapi.yaml -o site/openapi/index.html
          else
            echo "<!doctype html><title>No OpenAPI</title><p>No openapi/openapi.yaml</p>" > site/openapi/index.html
          fi
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
