name: Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: actions/setup-node@v5
        with:
          node-version: "20"
      - name: Build docs
        run: |
          pip install mkdocs mkdocs-material
          mkdocs build --strict
      - name: Build ReDoc
        run: |
          if [ -f openapi/openapi.yaml ]; then
            mkdir -p site/openapi
            npx --yes redoc-cli@0.13.23 bundle openapi/openapi.yaml -o site/openapi/index.html
          else
            mkdir -p site/openapi
            echo "<!doctype html><title>No OpenAPI</title><p>No openapi/openapi.yaml</p>" > site/openapi/index.html
          fi
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
