name: Pages
on:
  workflow_dispatch:
  push: { branches: [ main ] }
permissions:
  contents: read
  pages: write
  id-token: write
concurrency: { group: pages, cancel-in-progress: true }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with: { python-version: '3.11' }
      - name: Build MkDocs
        if: hashFiles('mkdocs.yml') != ''
        run: |
          python -m pip install -U pip
          pip install mkdocs mkdocs-material
          mkdocs build -d site
      - name: Fallback static
        if: hashFiles('mkdocs.yml') == ''
        run: |
          mkdir -p site && cp -r docs/* site/ || true
      - uses: actions/upload-pages-artifact@v4
        with: { path: site }
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
