---
name: release-artifacts

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev,ops] build schemathesis

      - name: Run unit tests
        run: pytest -q --maxfail=1

      - name: Build sdists/wheels
        run: python -m build

      - name: Read version from pyproject
        id: getver
        # yamllint disable rule:line-length
        run: |
          python -c "import tomllib;print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])" > version.txt
          echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
        # yamllint enable rule:line-length

      - name: Generate SBOM (SPDX JSON)
        uses: anchore/sbom-action@da167eac915b4e86f08b264dbdbc867b61be6f0c # v0.20.5
        with:
          path: .
          artifact-name: sbom.spdx.json
          format: spdx-json

      - name: Make canonical release ZIP
        run: bash scripts/release/make_release.sh
        env:
          VERSION_FALLBACK: ${{ steps.getver.outputs.version }}

      - name: Docker build
        # yamllint disable rule:line-length
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/neuron7x/factsynth:${{ steps.getver.outputs.version }} .
          docker push ghcr.io/neuron7x/factsynth:${{ steps.getver.outputs.version }}
        # yamllint enable rule:line-length

      - name: Trivy scan (fs)
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: factsynth-release
          path: |
            release/*.zip
            release/SHA256SUMS
            sbom.spdx.json
            dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2
        with:
          files: |
            release/*.zip
            release/SHA256SUMS
            sbom.spdx.json
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
