name: release-chart
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v4
      - name: Read version
        run: echo "VERSION=$(grep '^version = "' pyproject.toml | cut -d '"' -f2)" >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/factsynth:${{ env.VERSION }}
      - uses: azure/setup-helm@v4
      - name: Package chart
        run: helm package charts/factsynth --version $VERSION --app-version $VERSION
      - name: Push chart
        env:
          HELM_REGISTRY: ${{ env.REGISTRY }}/${{ github.repository_owner }}/charts
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
          helm push factsynth-$VERSION.tgz oci://$HELM_REGISTRY
