name: Release on Tag

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build release artifacts
        run: bash scripts/build_release.sh
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/dist/*
            release/CHECKSUMS.txt
