name: Release Artifact (manual)
on: { workflow_dispatch: {} }
permissions: { contents: read }
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create archive
        run: git archive -o factsynth.zip --format zip HEAD
      - uses: actions/upload-artifact@v4
        with: { name: factsynth-zip, path: factsynth.zip }
