name: scripts-quality
on: [push, pull_request]
jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install black ruff isort
      - run: python tools/scripts_calibrate.py --root scripts --write
      - run: make scripts.fmt
      - run: make scripts.lint

