name: Scripts Quality
on:
  pull_request: { branches: [ main ], paths: [ '**/*.sh' ] }
  push: { branches: [ main ], paths: [ '**/*.sh' ] }
permissions: { contents: read }
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-check
          level: error
          path: "."
          pattern: "**/*.sh"
