name: Spec verification

on:
  pull_request:
    paths:
      - "openapi/**"
      - "src/**"
      - "tests/**"

jobs:
  spec-verify:
    name: Spectral & Schemathesis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli

      - name: Run Spectral
        run: spectral lint openapi/openapi.yaml
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Schemathesis
        run: |
          python -m pip install -U pip
          pip install -e .[dev,ops] || pip install -e .
          pip install schemathesis uvicorn

      - name: Run Schemathesis
        if: always()
        run: |
          uvicorn src.factsynth_ultimate.app:app --port 8000 &
          pid=$!
          sleep 5
          schemathesis run --base-url=http://localhost:8000 openapi/openapi.yaml
          kill $pid
