name: Spec Verify
on:
  pull_request:
    branches: [ main ]
    paths: [ 'spec/**', 'openapi.*', '**/openapi.*' ]
  push:
    branches: [ main ]
    paths: [ 'spec/**', 'openapi.*', '**/openapi.*' ]
permissions: { contents: read }
jobs:
  spectral:
    if: hashFiles('spec/**','openapi.*','**/openapi.*') != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stoplightio/spectral-action@v0.12.0
        with:
          file_glob: |
            openapi.{yml,yaml,json}
            **/openapi.{yml,yaml,json}
            spec/**/*.{yml,yaml,json}
