name: trivy-scan
on:
  push:
    branches: [main]
  pull_request:
jobs:
  fs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: "os,library"
