name: ZipCI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create zip
        run: git archive -o factsynth-${{ github.sha }}.zip HEAD
      - uses: actions/upload-artifact@v4
        with:
          name: factsynth-zip
          path: factsynth-*.zip
